[project]
name = "hass-energy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
]

[project.scripts]
hass-energy = "hass_energy.cli:main"

[tool.uv]
package = true
